Updated StringAndCharacters.md
apple/swift-book pull request #281
Opened 2024-03-06 08:49 UTC by AbhishekSharma55

I Updated the grammar rule to allow for a tuple expression after the backslash, as shown in the following line:

interpolated-text-item → \( interpolated-text-list ) | quoted-text-item

The grammar rule for 'interpolated-text-item' specifies a single expression inside parentheses:

```
interpolated-text-item → \( expression ) | quoted-text-item
```

However, I've found that Swift actually accepts the equivalent of a tuple expression after the backslash, something like:

```
interpolated-text-item → \( interpolated-text-list ) | quoted-text-item
interpolated-text-list → interpolated-text-element | interpolated-text-element, interpolated-text-list
interpolated-text-element → expression | identifier : expression
```

I've corrected the grammar rule to allow for a tuple expression after the backslash, as shown in the following line:

```
interpolated-text-item → \( interpolated-text-list ) | quoted-text-item
```

Fixes: https://github.com/apple/swift-book/issues/282

2024-03-06 18:49 UTC, amartini51 requested changes
The issue described is about a fix to the formal grammar, but you edited a code listing in the guide to make an unrelated change.  The new code listing doesn't compile.

2024-03-06 19:00 UTC, amartini51 commented
I'm marking this as a draft.  If you'd like to try fixing the issue you linked to, please make you commits on the branch and then click Ready for review.  Thanks!

2024-03-07 02:55 UTC, AbhishekSharma55 commented
Hi @amartini51 ,

I hope you're doing well. Could you kindly provide more details on the changes required in the "String Interpolation" section? Any specific areas or aspects you'd like me to focus on would be helpful.

Thank you for your assistance.

Best regards,
@AbhishekSharma55

2024-03-07 19:12 UTC, amartini51 commented
@AbhishekSharma55 The bug https://github.com/apple/swift-book/issues/282 you linked to describes the problem with the grammar, and it includes a change to that grammar.  I suggest you start by making the change that the bug suggests, and then confirm that the change is correct.

2024-03-08 06:58 UTC, AbhishekSharma55 commented
Hi @amartini51 ,

Upon reviewing Issue #282, I've examined the grammar rule for "interpolated-text-item" to allow for a tuple expression after the backslash. I propose the following changes:

Change the rule from:
```
interpolated-text-item → \( expression ) | quoted-text-item
```
to:
```
interpolated-text-item → \( interpolated-text-list ) | quoted-text-item
```
Additionally, I suggest adding the following grammar rules:
```
interpolated-text-list → interpolated-text-element | interpolated-text-element, interpolated-text-list
interpolated-text-element → expression | identifier : expression
```

Should i move forward and create a PR

2024-03-08 16:49 UTC, amartini51 commented
@AbhishekSharma55 That is the proposed change from the person who filed the issue.  What did you do to confirm that it's the correct change to make to the grammar?

It seems like you might be looking for a starter bug to fix.  Fixes to the formal grammar are generally small, but not simple, and not usually a good starting point for working on the book.  You might have better luck with one of the GitHub issues tagged "Good first issue" instead.

https://github.com/apple/swift-book/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22

2024-03-22 17:29 UTC, amartini51 commented
@AbhishekSharma55 Do you still want to keep this PR open, or can I close it?

2024-03-22 19:46 UTC, closed without merging