Spell file-private with hyphen
apple/swift-book pull request #301
Opened 2024-05-05 13:27 UTC by SimplyDanny

The keyword `fileprivate` referred to in text is spelled in different ways throughout the book. "file-private" with a hyphen appears to me as the preferred style.

2024-05-05 16:12 UTC, krilnon requested changes
I think these are correct as-is. When we spell it "file-private" with the hyphen, it's being used as part of a compound adjective. Otherwise it's just "file private".

2024-05-05 16:33 UTC, SimplyDanny commented
> I think these are correct as-is. When we spell it "file-private" with the hyphen, it's being used as part of a compound adjective. Otherwise it's just "file private".

But isn't it always used as an adjective in these cases?

2024-05-06 17:31 UTC, amartini51 commented
Thanks for taking the time to look at these in the book.  I agree with Kyle — I think these follow our style the way they are.

We hyphenate when "file private" modifies the word that comes after it, like "a file-private function".

2024-05-08 19:21 UTC, closed without merging

2024-05-08 19:21 UTC, SimplyDanny commented
Okay, got the difference now. Compound adjectives preceding a noun are with hyphen, while standalone, they are written without one.

At least so I learned something new ...